# Generated by Django 4.2.19 on 2025-06-25 10:35

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email address", max_length=254, unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username for login",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.RegexValidator(
                                message="Username can only contain letters, numbers, underscores, and hyphens",
                                regex="^[a-zA-Z0-9_-]+$",
                            ),
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="user",
                        help_text="User role determines permissions",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether the email is verified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the news/event", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Description of the news/event"),
                ),
                (
                    "source_url",
                    models.URLField(help_text="Link to the original source"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="S3 URL for uploaded image", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_moderation", "Pending Moderation"),
                            ("pending_verification", "Pending Verification"),
                            ("rejected", "Rejected"),
                            ("live", "Live"),
                            ("disputed", "Disputed"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="pending_moderation",
                        help_text="Current status in the workflow",
                        max_length=30,
                    ),
                ),
                (
                    "moderation_result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Result from automated moderation",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (public)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When the post was verified", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted the post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        help_text="Name of the AI model (e.g., 'openai-gpt4')",
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField(help_text="AI's summary of the event")),
                (
                    "impact_assessment",
                    models.TextField(help_text="AI's assessment of impact"),
                ),
                (
                    "objectivity_analysis",
                    models.TextField(help_text="AI's analysis of objectivity"),
                ),
                (
                    "key_quotes",
                    models.JSONField(
                        default=list, help_text="Important quotes identified by AI"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (model version, temperature, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Post this response is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_responses",
                        to="api.post",
                    ),
                ),
            ],
            options={
                "db_table": "ai_responses",
                "ordering": ["ai_model"],
            },
        ),
        migrations.CreateModel(
            name="VerificationVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.BooleanField(
                        help_text="True = accurate, False = inaccurate"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment about the verification"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Post being verified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_votes",
                        to="api.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who cast the vote",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "verification_votes",
                "ordering": ["-created_at"],
                "unique_together": {("user", "post")},
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-created_at"], name="posts_status_ecf387_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="airesponse",
            unique_together={("post", "ai_model")},
        ),
    ]
