# Generated by Django 4.2.19 on 2025-07-05 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_email_verification_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the post was moderated", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who moderated this post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
