# Generated by Django 4.2.19 on 2025-07-05 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_moderation_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True, help_text="S3 URL for user avatar", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, help_text="User biography/description", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="github_username",
            field=models.CharField(
                blank=True,
                help_text="GitHub username",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="GitHub username can only contain letters, numbers, and hyphens",
                        regex="^[a-zA-Z0-9-]+$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_username",
            field=models.CharField(
                blank=True,
                help_text="Twitter/X username without @",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Twitter username can only contain letters, numbers, and underscores",
                        regex="^[a-zA-Z0-9_]+$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website_url",
            field=models.URLField(
                blank=True, help_text="User's personal website", null=True
            ),
        ),
    ]
