# Generated by Django 4.2.19 on 2025-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_avatar_url_user_bio_user_github_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive failed login attempts"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_failed_login",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last failed login attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Account locked until this timestamp", null=True
            ),
        ),
    ]
