# Generated by Django 4.2.19 on 2025-07-10 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_account_lockout_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username at time of action (preserved if user deleted)",
                        max_length=150,
                    ),
                ),
                (
                    "user_id_snapshot",
                    models.IntegerField(
                        help_text="User ID at time of action", null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("auth", "Authentication"),
                            ("user", "User Management"),
                            ("moderation", "Content Moderation"),
                            ("admin", "Administrative"),
                            ("security", "Security"),
                            ("data", "Data Access"),
                        ],
                        db_index=True,
                        help_text="Category of action",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Specific action performed",
                        max_length=50,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action succeeded"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Request correlation ID",
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of resource affected (e.g., 'post', 'user')",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.IntegerField(
                        blank=True, help_text="ID of the resource affected", null=True
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data (automatically redacted)",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the action (e.g., moderation reason)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "permissions": [
                    ("view_audit_logs", "Can view audit logs"),
                    ("export_audit_logs", "Can export audit logs"),
                ],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "category"],
                        name="audit_logs_timesta_5827d9_idx",
                    ),
                    models.Index(
                        fields=["user_id_snapshot", "-timestamp"],
                        name="audit_logs_user_id_eb5abb_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_logs_action_f48619_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                ],
            },
        ),
    ]
